# call-tester config
# sudo systemctl stop ModemManager && sudo systemctl disable ModemManager
# sudo apt install -y libqmi-utils udhcpc curl

metrics:
  enabled: true
  listen: "0.0.0.0:9100"

modems:
  - name: ec25_1
    at_port: /dev/ttyUSB2
    qmi_device: /dev/cdc-wdm0
    net_iface: wwan0
    baud_rate: 115200
    model: Quectel EC25-EUX
    phone_number: "+77076423712"
    apn: "internet"
    apn_user: ""
    apn_pass: ""
    operator: Tele2

  - name: ec25_2
    at_port: /dev/ttyUSB6
    qmi_device: /dev/cdc-wdm1
    net_iface: wwan1
    baud_rate: 115200
    model: Quectel EC25-EUX
    phone_number: "+77076421165"
    apn: "internet"
    apn_user: ""
    apn_pass: ""
    operator: Tele2
